### ISSUE TITLE
Deprecated node12, migrate to node 16

### ISSUE THREAD

**Issue by jellespijker** [Apple-Actions/import-codesign-certs#28]
Hi,

Since I'm more of a C++/Python dev I don't known if the warning from our runners is a concern that needs to be addressed but as of today we received the following warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: apple-actions/import-codesign-certs

https://github.com/Ultimaker/Cura/actions/runs/3232797852

**Comment by FelixLisczyk** [comment]
There is another deprecation warning when using this action:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by ssrobins** [comment]
Posted a pull request that addresses this: https://github.com/Apple-Actions/import-codesign-certs/pull/41
