### ISSUE TITLE
`set-output` deprecated in GitHub Actions 

### ISSUE THREAD

**Issue by JinoArch** [Apple-Actions/import-codesign-certs#29]
I see following issue while running GitHub Actions. 

![Screenshot 2022-10-31 at 11 22 18 PM](https://user-images.githubusercontent.com/39610834/199075701-1a69a5ed-90d8-4369-8a5f-ef50ebd781d5.png)

Looks like we need to update code for the same?

**Comment by ssrobins** [comment]
Posted a pull request that addresses this: https://github.com/Apple-Actions/import-codesign-certs/pull/41
