### ISSUE TITLE
Project needs repackaging and re-release to work with GitHub Actions

### ISSUE THREAD

**Issue by rolfb** [Apple-Actions/import-codesign-certs#40]
Trying to use the tip of this repository (cf6971f61e83048ac220cc3d7f580cc178630cb4) in a workflow on GitHub Actions causes the following error:

`milliseconds not a number`

@orj This seems to be thrown from the old dist/index.js file, so perhaps this project needs a repackaging and a new release to GitHub marketplace?

**Comment by ssrobins** [comment]
Posted a pull request that addresses this: https://github.com/Apple-Actions/import-codesign-certs/pull/41
