### ISSUE TITLE
v2 tag

### ISSUE THREAD

**Issue by alexjurkiewicz** [Apple-Actions/import-codesign-certs#48]
Hello, I saw the v2 tag was pushed, but there's no release of this or update to the actions marketplace listing. Is the v2 tag ready to use?

**Comment by loayei** [comment]
+1

**Comment by steveoh** [comment]
will you update this please

<img width="162" alt="image" src="https://user-images.githubusercontent.com/325813/229610524-a708f996-6eeb-4200-a81f-a9619876fb7a.png">

**Comment by ssrobins** [comment]
Done!

**Comment by ReenigneArcher** [comment]
Same for v6.1.0 and v7.0.0?
