### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by pllim** [Apple-Actions/import-codesign-certs#57]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: apple-actions/import-codesign-certs@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

https://github.com/Apple-Actions/import-codesign-certs/blob/5565bb656f60c98c8fc515f3444dd8db73545dc2/action.yml#L31

**Comment by grzegorzkrukowski** [comment]
[GitHub announced](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/) that they will enforce node20 instead of a warning on 13th May

**Comment by paulmcgrathparamount** [comment]
There's a PR awaiting merging for this issue - https://github.com/Apple-Actions/import-codesign-certs/pull/58 - but in the meantime one workaround I found was to check the logs of the git workflow where this action is called and copying the security commands output by the script. Then I just replace the invocation of this action with running those commands directly. Probably not an ideal solution but it does get rid of the deprecation warning.

**Comment by ssrobins** [comment]
Upgraded with https://github.com/Apple-Actions/import-codesign-certs/pull/64

**Comment by pllim** [comment]
Thanks!
